runtime: nodejs10
handlers:
  - url: /(.*\.(gif|media|json|ico|eot|ttf|woff|woff2|png|jpg|svg|css|js))$
    static_files: build/\1
    upload: build/.*\.(gif|media|json|ico|eot|ttf|woff|woff2|png|jpg|svg|css|js)$
  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
